# -*- coding: utf-8 -*-
"""Sals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mzwJTO-9L75LYZM7K-f8insGGavogbuE
"""

#   E-COMMERCE SALES ANALYSIS - CLEAN PIPELINE

import pandas as pd
import matplotlib.pyplot as plt
import os
from IPython.display import display

 # 1. Load Dataset
 DATA_PATH = "/content/online_retail_II.csv"

df = pd.read_csv(DATA_PATH, encoding='latin1', low_memory=False)

print("File Loaded Successfully")
print("Path:", DATA_PATH)
print("Rows:", len(df))
print("Columns:", list(df.columns))

print("\n--- SAMPLE (first 8 rows) ---")
display(df.head(8))

"""This dataset represents transactional data from an online retail store, capturing detailed information about customer purchases. Each row corresponds to a single product item within an invoice, including the invoice number, product code, product description, quantity purchased, transaction date and time, unit price, customer identifier, and country of purchase. The data primarily reflects sales activity from the United Kingdom, indicating that it is the store’s main market. Multiple products can appear under the same invoice, showing that customers often purchase several items in a single transaction. The presence of customer IDs enables customer-level analysis such as purchase frequency and spending behavior, while invoice dates allow for time-based trend analysis. Overall, this dataset is well-suited for exploratory data analysis, sales trend evaluation, customer segmentation, and business insight generation for e-commerce analytics."""

# 2. Basic Information + Missing Values
 print("\n--- DATA INFO ---")
df.info()

print("\n--- MISSING VALUE SUMMARY ---")
missing = df.isna().sum().sort_values(ascending=False)
display(missing.to_frame("Missing_Count"))

"""The dataset contains 12,304 transaction records across 8 columns, comprising both numerical and categorical variables. Core transactional fields such as Invoice, StockCode, Quantity, InvoiceDate, Price, and Country are fully populated, ensuring strong data completeness for sales and time-series analysis. The data includes numeric variables (Price, Quantity, Customer ID) and categorical attributes related to products and geography. Minor missing values are present in the Description column (45 records), while Customer ID has a higher number of missing entries (3,505), indicating anonymous or unregistered customers. This impacts customer-level analysis (e.g., RFM, segmentation) but does not limit overall sales trends, product performance, or country-level insights, making the dataset suitable for EDA and business intelligence analysis."""

# 3. Data Cleaning

cleaned = df.copy()

# Convert dates
if 'InvoiceDate' in cleaned.columns:
    cleaned['InvoiceDate'] = pd.to_datetime(cleaned['InvoiceDate'], errors='coerce')

# Convert numeric fields
for col in ['Quantity', 'Price']:
    if col in cleaned.columns:
        cleaned[col] = pd.to_numeric(cleaned[col], errors='coerce')

# Create Revenue Column
if 'Quantity' in cleaned.columns and 'Price' in cleaned.columns:
    cleaned['Revenue'] = cleaned['Quantity'] * cleaned['Price']

# Remove invalid rows
cleaned = cleaned[cleaned['InvoiceDate'].notna()]        # drop rows without date
cleaned = cleaned.dropna(subset=['StockCode','Description'])

print("\nRows after cleaning:", len(cleaned))

# 4. Filter sales-only (exclude returns)
 sales = cleaned[(cleaned['Quantity'] > 0) & (cleaned['Price'] > 0)].copy()

print("Rows in SALES table:", len(sales))

# 5. Aggregated Tables

# Top-selling products
top_products = (
    sales.groupby(['StockCode', 'Description'])
         .agg(TotalRevenue=('Revenue','sum'),
              TotalQty=('Quantity','sum'),
              OrderCount=('Invoice','nunique' if 'Invoice' in sales.columns else 'count'))
         .reset_index()
         .sort_values('TotalRevenue', ascending=False)
)

# Monthly revenue trend
monthly_summary = (
    sales
    .set_index('InvoiceDate')
    .resample('M')
    .agg(MonthlyRevenue=('Revenue','sum'),
         MonthlyQty=('Quantity','sum'))
    .reset_index()
)

# Revenue by country
if 'Country' in sales.columns:
    country_summary = (
        sales.groupby('Country')
             .agg(TotalRevenue=('Revenue','sum'),
                  TotalQty=('Quantity','sum'))
             .reset_index()
             .sort_values('TotalRevenue', ascending=False)
    )
else:
    country_summary = None

print("\n--- TOP PRODUCTS SAMPLE ---")
display(top_products.head(10))

print("\n--- MONTHLY SUMMARY SAMPLE ---")
display(monthly_summary.head(10))

if country_summary is not None:
    print("\n--- COUNTRY SUMMARY SAMPLE ---")
    display(country_summary.head(10))

"""Top-selling products like REGENCY CAKESTAND 3 TIER and WHITE HANGING HEART T-LIGHT HOLDER drive the highest revenue through high orders and volume. Monthly sales show seasonal trends with gaps likely due to missing data. United Kingdom dominates sales, while Germany, EIRE, and France contribute smaller international revenue. These insights highlight key products, seasonal trends, and target markets for business strategy."""

# 6. Save Clean Files

OUTPUT_DIR = "/mnt/data/cleaned_outputs"
os.makedirs(OUTPUT_DIR, exist_ok=True)

cleaned_file = f"{OUTPUT_DIR}/cleaned_full_dataset.csv"
sales_file = f"{OUTPUT_DIR}/sales_only.csv"
top_products_file = f"{OUTPUT_DIR}/top_products.csv"
monthly_file = f"{OUTPUT_DIR}/monthly_summary.csv"
country_file = f"{OUTPUT_DIR}/country_summary.csv"

cleaned.to_csv(cleaned_file, index=False)
sales.to_csv(sales_file, index=False)
top_products.to_csv(top_products_file, index=False)
monthly_summary.to_csv(monthly_file, index=False)
if country_summary is not None:
    country_summary.to_csv(country_file, index=False)

print("\n Files Saved To:", OUTPUT_DIR)

# 7. Visualizations (default matplotlib colors)

# Monthly Revenue Trend
plt.figure(figsize=(12,5))
plt.plot(monthly_summary['InvoiceDate'], monthly_summary['MonthlyRevenue'])
plt.title("Monthly Revenue Trend")
plt.xlabel("Month")
plt.ylabel("Revenue")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Top 20 Products by Revenue
plt.figure(figsize=(10,7))
top20 = top_products.head(20)
plt.barh(top20['Description'].iloc[::-1], top20['TotalRevenue'].iloc[::-1])
plt.title("Top 20 Products by Revenue")
plt.xlabel("Revenue")
plt.tight_layout()
plt.show()

# Country Revenue Chart
if country_summary is not None:
    plt.figure(figsize=(12,6))
    plt.bar(country_summary['Country'].head(10), country_summary['TotalRevenue'].head(10))
    plt.title("Top 10 Countries by Revenue")
    plt.xlabel("Country")
    plt.ylabel("Revenue")
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

print("\n Analysis Complete!")

"""The country-wise revenue chart shows that the United Kingdom dominates sales, contributing the vast majority of total revenue, while other countries like Germany, EIRE, and France have smaller but noticeable contributions.

The product-wise revenue chart highlights top-selling items such as REGENCY CAKESTAND 3 TIER, DOTCOM POSTAGE, and BLACK RECORD COVER FRAME, which generate the highest revenue due to a combination of high demand and order frequency. These visualizations provide clear insights into key markets and high-performing products, useful for targeted marketing and inventory planning.
"""
